[package]
name = "pdftomobi-ebook"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pdftomobi-core = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

zip  = { version = "2", default-features = false, features = ["deflate"] }
uuid = { version = "1", features = ["v4"] }
which = "7"
